// Silly Pinball — sound.
//
// WAV only, and never through Web Audio: JavaFX WebView has no AudioContext at all, and its
// HTML5 <audio> runs through jfxmedia, which rejects MP3 and OGG. PCM WAV plays fine, so
// every effect ships as a committed .wav (generated by tools/make-sounds.sh, which is a dev
// tool — nothing at runtime calls it).
//
// Every call here is defensive: a missing or broken audio stack must leave the game silent,
// never broken (Review Focus #4).
const Sound = (() => {
  const POOL = 3;
  const NAMES = [
    'flipper', 'bumper1', 'bumper2', 'bumper3', 'sling', 'target', 'bank', 'spinner',
    'kicker', 'launch', 'drain', 'save', 'extra', 'multiball', 'cheer', 'nudge', 'tilt',
  ];

  const pools = {};
  const cursor = {};
  let muted = false;
  let ready = false;

  function init(dir) {
    try {
      for (const name of NAMES) {
        const list = [];
        for (let i = 0; i < POOL; i++) {
          const a = new Audio(dir + '/' + name + '.wav');
          a.preload = 'auto';
          list.push(a);
        }
        pools[name] = list;
        cursor[name] = 0;
      }
      ready = true;
    } catch (e) {
      ready = false;          // leave Sound inert rather than half-built
    }
  }

  /** Returns the Audio element it played (or null); errors never escape. */
  function play(name) {
    if (!ready || muted) return null;
    const list = pools[name];
    if (!list || !list.length) return null;
    try {
      const a = list[cursor[name]];
      cursor[name] = (cursor[name] + 1) % list.length;
      a.currentTime = 0;
      const p = a.play();
      if (p && p.catch) p.catch(function () { /* autoplay/format refusals are not fatal */ });
      return a;
    } catch (e) {
      return null;
    }
  }

  function toggleMute() {
    muted = !muted;
    return muted;
  }

  function isMuted() {
    return muted;
  }

  function isReady() {
    return ready;
  }

  return { init, play, toggleMute, isMuted, isReady, NAMES };
})();
